import { useCallback, useEffect, useMemo, useState } from 'react';
import { toast } from 'sonner';
import { apiJson, cleanErpCode } from '../../lib';
import { useQuoteCart } from '../../context/QuoteCartContext';
import type { OfficialVerification, PartDetail } from '../../types';
import { effectivePartNumber, isSupersededForCode, officialPortalLabel, officialPortalUrl, VerificationBadge } from '../PartVerificationDialog';
import { recordQuoteUsage } from './quoteUsage';
import SourceBadge from './SourceBadge';
import type { HusqvarnaLivePart, WorkContext } from './types';

type Props = { detail: PartDetail; verification?: OfficialVerification; verificationLoading?: boolean; liveData: HusqvarnaLivePart | null; onClose: () => void; onCopy: (code: string) => void; onOpenPdf: (documentId: string, page: number | null, title: string) => void; onOpenRelated: (id: string) => void; onToggleFavorite: () => void; onVerify: () => void; onCrossReference: (code: string, name: string) => void; onAskAi: (prompt: string) => void };

function money(value?: number | null) { return value == null ? null : new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(value); }
function SmallPartAction({ code, name, extra, onCopy }: { code: string; name: string; extra?: string; onCopy: (code: string) => void }) { const rawCode = cleanErpCode(code); return <div className="flex items-center justify-between gap-3 rounded-xl bg-slate-50 px-3 py-2.5 dark:bg-slate-800/60"><div className="min-w-0"><div className="truncate text-xs font-black text-slate-800 dark:text-slate-100">{name}</div><div className="mt-0.5 flex flex-wrap items-center gap-2 text-[10px] text-slate-400"><span className="font-mono font-bold text-[#1d4f91] dark:text-blue-300">{rawCode}</span>{extra && <span>{extra}</span>}</div></div><button type="button" onClick={() => onCopy(rawCode)} className="shrink-0 rounded-lg border border-slate-200 bg-white px-2.5 py-1.5 text-[10px] font-black text-slate-600 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-300">Copiar</button></div>; }

export default function PartDetailDrawer({ detail, verification, verificationLoading = false, liveData, onClose, onCopy, onOpenPdf, onOpenRelated, onToggleFavorite, onVerify, onCrossReference, onAskAi }: Props) {
  const quoteCart = useQuoteCart();
  const [moreOpen, setMoreOpen] = useState(false);
  const [workContext, setWorkContext] = useState<WorkContext | null>(null);
  const [contextLoading, setContextLoading] = useState(true);
  const [locationEditing, setLocationEditing] = useState(false);
  const [location, setLocation] = useState('');
  const [locationNote, setLocationNote] = useState('');
  const [savingLocation, setSavingLocation] = useState(false);
  const superseded = isSupersededForCode(detail.partNumber, verification);
  const effectiveCode = cleanErpCode(effectivePartNumber(detail.partNumber, verification));
  const originalCode = cleanErpCode(detail.partNumber);
  const price = money(detail.price);
  const inCart = useMemo(() => quoteCart.items.find(item => cleanErpCode(item.partNumber) === effectiveCode && item.model === detail.model), [detail.model, effectiveCode, quoteCart.items]);

  const loadContext = useCallback(async () => {
    setContextLoading(true);
    try { const data = await apiJson<{ context: WorkContext }>(`/api/parts/${encodeURIComponent(effectiveCode)}/work-context?model=${encodeURIComponent(detail.model)}`); setWorkContext(data.context); setLocation(data.context.location?.value || ''); setLocationNote(data.context.location?.note || ''); } catch { setWorkContext(null); } finally { setContextLoading(false); }
  }, [detail.model, effectiveCode]);
  useEffect(() => { const timer = window.setTimeout(() => void loadContext(), 0); return () => window.clearTimeout(timer); }, [loadContext]);

  const addToQuote = () => { recordQuoteUsage([...quoteCart.items, { partNumber: effectiveCode, model: detail.model }], quoteCart.items.length === 0); quoteCart.addItem({ partNumber: effectiveCode, effectiveCode, name: detail.name, model: detail.model, pnc: detail.pnc, section: detail.section, position: detail.position, filename: detail.filename, page: detail.page, isSuperseded: superseded, originalCode: superseded ? originalCode : undefined, notes: detail.notes, unitPrice: detail.price ?? undefined }); };
  const sendWhatsApp = () => { const text = [`*${detail.name}*`, `Código: ${effectiveCode}`, `Aplicação: ${detail.model}${detail.pnc ? ` · PNC ${detail.pnc}` : ''}`, price ? `Preço: ${price}` : null].filter(Boolean).join('\n'); window.open(`https://wa.me/?text=${encodeURIComponent(text)}`, '_blank', 'noopener,noreferrer'); };
  const saveLocation = async () => { const clean = location.trim(); if (!clean) { toast.error('Informe a localização física da peça.'); return; } setSavingLocation(true); try { await apiJson(`/api/parts/${encodeURIComponent(effectiveCode)}/location`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ location: clean, note: locationNote.trim() }) }); toast.success('Localização compartilhada atualizada.'); setLocationEditing(false); await loadContext(); } catch (error) { toast.error(error instanceof Error ? error.message : 'Não foi possível salvar a localização.'); } finally { setSavingLocation(false); } };
  const officialUrl = liveData?.originalPartUrl || verification?.officialUrl || officialPortalUrl(effectiveCode, detail.manufacturer);
  const sources = workContext?.sources || [];

  return <div className="fixed inset-0 z-[75] flex justify-end"><button type="button" aria-label="Fechar detalhe" onClick={onClose} className="absolute inset-0 bg-slate-950/45 backdrop-blur-[2px]" /><section className="relative z-10 flex h-full w-full max-w-[900px] flex-col bg-[#f5f7fa] shadow-2xl dark:bg-slate-950">
    <header className="flex shrink-0 items-start justify-between gap-4 border-b border-slate-200 bg-white px-5 py-4 dark:border-slate-800 dark:bg-slate-900 sm:px-7"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="text-[10px] font-black uppercase tracking-[.15em] text-[#1d4f91] dark:text-blue-300">Detalhe da peça</span><SourceBadge source="CATALOG" compact />{sources.filter(source => source.type !== 'CATALOG').map(source => <SourceBadge key={`${source.type}:${source.detail}`} source={source.type} detail={source.detail} compact />)}</div><h2 className="mt-1 truncate text-xl font-black tracking-[-.02em] text-slate-950 dark:text-white">{detail.name}</h2></div><button type="button" onClick={onClose} className="rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs font-bold text-slate-600 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-300">Fechar <span className="ml-1 text-[9px] text-slate-400">Esc</span></button></header>
    <div className="cv-scrollbar min-h-0 flex-1 overflow-y-auto p-4 sm:p-6"><div className="grid gap-4 lg:grid-cols-[minmax(0,1.55fr)_minmax(260px,.85fr)]"><div className="space-y-4">
      <section className="overflow-hidden rounded-2xl bg-[#0d2b55] text-white shadow-[0_14px_35px_rgba(13,43,85,.16)]"><div className="p-5 sm:p-6"><div className="text-[10px] font-black uppercase tracking-[.13em] text-blue-200">Código da peça</div><div className="mt-2 break-all font-mono text-3xl font-black tracking-[-.04em]">{effectiveCode}</div>{superseded && <div className="mt-1 text-xs text-blue-200">Código anterior: {originalCode}</div>}<div className="mt-5 grid gap-2 sm:grid-cols-2"><button type="button" onClick={() => onCopy(effectiveCode)} className="rounded-xl bg-white px-4 py-3 text-sm font-black text-[#123867]">Copiar código</button><button type="button" onClick={addToQuote} className="rounded-xl bg-amber-400 px-4 py-3 text-sm font-black text-slate-950">{inCart ? `No orçamento (${inCart.quantity})` : '+ Adicionar ao orçamento'}</button></div><div className="mt-2 grid grid-cols-2 gap-2 sm:grid-cols-3"><button type="button" onClick={sendWhatsApp} className="rounded-xl border border-white/15 bg-white/10 px-3 py-2.5 text-xs font-bold">WhatsApp</button><button type="button" onClick={() => onOpenPdf(detail.documentId, detail.page, detail.filename)} className="rounded-xl border border-white/15 bg-white/10 px-3 py-2.5 text-xs font-bold">Abrir catálogo</button><button type="button" onClick={() => onCrossReference(effectiveCode, detail.name)} className="rounded-xl border border-white/15 bg-white/10 px-3 py-2.5 text-xs font-bold">Onde usa?</button></div><div className="relative mt-2"><button type="button" onClick={() => setMoreOpen(open => !open)} className="rounded-xl border border-white/15 bg-white/10 px-3 py-2 text-[11px] font-bold text-blue-100">Mais ações ···</button>{moreOpen && <div className="absolute left-0 top-11 z-20 w-60 rounded-xl border border-slate-200 bg-white p-1.5 text-slate-700 shadow-xl dark:border-slate-700 dark:bg-slate-800 dark:text-slate-200"><button type="button" onClick={() => { setMoreOpen(false); onToggleFavorite(); }} className="w-full rounded-lg px-3 py-2 text-left text-xs font-bold">{detail.favoriteId ? 'Remover dos favoritos' : 'Favoritar peça'}</button><button type="button" onClick={() => { setMoreOpen(false); onAskAi(`Analise a peça ${detail.name}, código ${effectiveCode}, aplicada em ${detail.model}.`); }} className="w-full rounded-lg px-3 py-2 text-left text-xs font-bold">Perguntar à IA</button><a href={officialUrl} target="_blank" rel="noreferrer" className="block rounded-lg px-3 py-2 text-xs font-bold">{officialPortalLabel(effectiveCode, detail.manufacturer)} ↗</a></div>}</div></div></section>
      {(liveData?.name || liveData?.imageUrl || liveData?.specifications) && <section className="rounded-2xl border border-emerald-200 bg-emerald-50/70 p-4 dark:border-emerald-900 dark:bg-emerald-950/20"><div className="flex flex-wrap items-start gap-4">{liveData.imageUrl && <div className="grid h-28 w-32 shrink-0 place-items-center overflow-hidden rounded-xl border border-emerald-100 bg-white p-2 dark:border-emerald-900 dark:bg-slate-900"><img src={liveData.imageUrl} alt={liveData.name || detail.name} className="max-h-full max-w-full object-contain" /></div>}<div className="min-w-0 flex-1"><div className="flex items-center gap-2"><SourceBadge source="OFFICIAL" compact /><span className="text-[10px] font-black uppercase tracking-[.12em] text-emerald-700 dark:text-emerald-300">Dados ao vivo Husqvarna</span></div><div className="mt-2 text-sm font-black text-slate-900 dark:text-white">{liveData.name || detail.name}</div></div></div></section>}
      <section className="rounded-2xl border border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-900"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="text-[10px] font-black uppercase tracking-[.12em] text-slate-400">Localização física</div><div className="mt-1 text-sm font-black text-slate-900 dark:text-white">Onde pegar esta peça</div></div><button type="button" onClick={() => setLocationEditing(editing => !editing)} className="rounded-lg border border-slate-200 px-3 py-1.5 text-[10px] font-black text-[#1d4f91] dark:border-slate-700 dark:text-blue-300">{locationEditing ? 'Cancelar' : workContext?.location ? 'Alterar' : '+ Cadastrar'}</button></div>{contextLoading ? <div className="mt-3 h-14 animate-pulse rounded-xl bg-slate-100 dark:bg-slate-800" /> : locationEditing ? <div className="mt-3 grid gap-2"><input value={location} onChange={event => setLocation(event.target.value)} maxLength={160} placeholder="Ex.: Estoque principal · Corredor 2 · Prateleira A4" className="rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm dark:border-slate-700 dark:bg-slate-800" /><input value={locationNote} onChange={event => setLocationNote(event.target.value)} maxLength={500} placeholder="Observação opcional" className="rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-xs dark:border-slate-700 dark:bg-slate-800" /><button type="button" disabled={savingLocation} onClick={() => void saveLocation()} className="justify-self-start rounded-xl bg-[#123867] px-4 py-2 text-xs font-black text-white disabled:opacity-50">{savingLocation ? 'Salvando…' : 'Salvar para a equipe'}</button></div> : workContext?.location ? <div className="mt-3 rounded-xl bg-blue-50 px-4 py-3 dark:bg-blue-950/25"><div className="text-sm font-black text-[#123867] dark:text-blue-300">{workContext.location.value}</div>{workContext.location.note && <div className="mt-1 text-xs text-slate-500 dark:text-slate-400">{workContext.location.note}</div>}</div> : <div className="mt-3 rounded-xl border border-dashed border-slate-200 px-4 py-4 text-xs text-slate-400 dark:border-slate-700">Localização ainda não cadastrada.</div>}</section>
      <section className="grid gap-3 sm:grid-cols-2">{[['Modelo', detail.model], ['PNC', detail.pnc || '—'], ['Seção', detail.section || '—'], ['Posição / página', `${detail.position || '—'} · pág. ${detail.page || '—'}`]].map(([label, value]) => <div key={label} className="rounded-2xl border border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-900"><div className="text-[9px] font-black uppercase tracking-[.12em] text-slate-400">{label}</div><div className="mt-1 text-sm font-black text-slate-900 dark:text-white">{value}</div></div>)}</section>
      {detail.suggestedAddons && detail.suggestedAddons.items.length > 0 && <section className="rounded-2xl border border-blue-200 bg-white p-4 dark:border-blue-900 dark:bg-slate-900"><div className="text-[10px] font-black uppercase tracking-[.12em] text-blue-600 dark:text-blue-300">Sugestões para esta máquina</div><p className="mt-1 text-[11px] text-slate-400">{detail.suggestedAddons.reason}</p><div className="mt-3 space-y-2">{detail.suggestedAddons.items.map(item => <button key={item.id} type="button" onClick={() => onOpenRelated(item.id)} className="flex w-full items-center justify-between gap-3 rounded-xl bg-blue-50/70 px-3 py-2.5 text-left"><span className="min-w-0"><span className="block truncate text-xs font-black text-slate-800 dark:text-slate-100">{item.name}</span><span className="mt-0.5 block font-mono text-[10px] font-bold text-[#1d4f91]">{cleanErpCode(item.partNumber)}</span></span><span className="text-[10px] font-black text-[#1d4f91]">Abrir →</span></button>)}</div></section>}
    </div><aside className="space-y-4"><section className="rounded-2xl border border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center justify-between gap-2"><div><div className="text-[10px] font-black uppercase tracking-[.12em] text-slate-400">Confiabilidade</div><div className="mt-1 text-sm font-black text-slate-900 dark:text-white">Fontes desta peça</div></div><VerificationBadge verification={verification} loading={verificationLoading} /></div><div className="mt-3 flex flex-wrap gap-2"><SourceBadge source="CATALOG" />{workContext?.sources.filter(source => source.type !== 'CATALOG').map(source => <SourceBadge key={`${source.type}:${source.detail}`} source={source.type} detail={source.detail} />)}{liveData && <SourceBadge source="OFFICIAL" />}</div><div className="mt-3 flex flex-wrap gap-2"><button type="button" onClick={onVerify} className="rounded-lg border border-slate-200 px-3 py-2 text-[10px] font-bold text-slate-600 dark:border-slate-700 dark:text-slate-300">Registrar conferência</button><a href={officialUrl} target="_blank" rel="noreferrer" className="rounded-lg border border-slate-200 px-3 py-2 text-[10px] font-bold text-[#1d4f91] dark:border-slate-700 dark:text-blue-300">Fonte oficial ↗</a></div></section>
      <section className="rounded-2xl border border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-900"><div className="text-[10px] font-black uppercase tracking-[.12em] text-slate-400">Mais procuradas</div><div className="mt-1 text-sm font-black text-slate-900 dark:text-white">Nesta máquina</div><div className="mt-3 space-y-2">{workContext?.popularParts.length ? workContext.popularParts.slice(0, 6).map(item => <SmallPartAction key={item.partNumber} code={item.partNumber} name={item.name} extra={`${item.count} consulta${item.count === 1 ? '' : 's'}`} onCopy={onCopy} />) : <div className="rounded-xl bg-slate-50 px-3 py-4 text-center text-[11px] leading-5 text-slate-400 dark:bg-slate-800/60">Ainda não há histórico suficiente para este modelo.</div>}</div></section>
      <section className="rounded-2xl border border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-900"><div className="text-[10px] font-black uppercase tracking-[.12em] text-slate-400">Costumam sair junto</div><div className="mt-1 text-sm font-black text-slate-900 dark:text-white">Baseado em orçamentos reais</div><div className="mt-3 space-y-2">{workContext?.togetherReady && workContext.frequentlyTogether.length ? workContext.frequentlyTogether.slice(0, 6).map(item => <SmallPartAction key={item.partNumber} code={item.partNumber} name={item.name} extra={`${item.percentage}% dos atendimentos`} onCopy={onCopy} />) : <div className="rounded-xl border border-dashed border-slate-200 px-3 py-4 text-center text-[11px] leading-5 text-slate-400 dark:border-slate-700">O CogniVault ainda está aprendendo. Essa recomendação só aparece depois de pelo menos 3 atendimentos com esta peça.</div>}</div></section>
      <section className="rounded-2xl border border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-900"><div className="text-[10px] font-black uppercase tracking-[.12em] text-slate-400">Peças da mesma vista</div><div className="mt-1 text-sm font-black text-slate-900 dark:text-white">Contexto do desenho técnico</div><div className="mt-3 space-y-2">{detail.related.length ? detail.related.map(item => <button key={item.id} type="button" onClick={() => onOpenRelated(item.id)} className="w-full rounded-xl bg-slate-50 px-3 py-2.5 text-left dark:bg-slate-800/60"><div className="truncate text-xs font-black text-slate-800 dark:text-slate-100">{item.name}</div><div className="mt-1 flex items-center justify-between gap-2 text-[10px] text-slate-400"><span className="font-mono font-bold text-[#1d4f91]">{cleanErpCode(item.partNumber)}</span><span>{item.position ? `Pos. ${item.position}` : ''}</span></div></button>) : <div className="rounded-xl bg-slate-50 px-3 py-4 text-center text-[11px] text-slate-400 dark:bg-slate-800/60">Nenhuma outra peça da vista encontrada.</div>}</div></section>
    </aside></div></div></section></div>;
}
