import { FormEvent, useEffect, useState } from 'react';
import { api, fmtDate, json } from '../lib';
import type { AdminUser, AuditLog, Overview, Role } from '../types';

export function OverviewPanel(){
 const [data,setData]=useState<Overview|null>(null);useEffect(()=>{void (async()=>setData((await json<{overview:Overview}>(await api('/api/admin/overview'))).overview))()},[]);
 const cards=data?[['Catálogos ativos',data.activeDocuments],['Peças indexadas',data.parts],['Usuários ativos',data.users],['Acerto confirmado',data.feedbackAccuracy===null?'—':`${Math.round(data.feedbackAccuracy*100)}%`]]:[];
 return <section><p className="text-xs font-bold uppercase tracking-[.15em] text-indigo-600">Administração</p><h1 className="text-2xl font-bold mt-1">Visão geral</h1><div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-4 mt-6">{cards.map(([k,v])=><div key={String(k)} className="bg-white border border-slate-200 rounded-2xl p-5"><div className="text-sm text-slate-500">{k}</div><div className="text-3xl font-bold mt-2">{v}</div></div>)}</div>{data&&<div className="grid md:grid-cols-3 gap-4 mt-4"><div className="bg-amber-50 rounded-2xl p-5"><b>{data.processingDocuments}</b><div className="text-sm text-amber-800">em processamento</div></div><div className="bg-rose-50 rounded-2xl p-5"><b>{data.failedDocuments}</b><div className="text-sm text-rose-800">com falha</div></div><div className="bg-indigo-50 rounded-2xl p-5"><b>{data.feedbackTotal}</b><div className="text-sm text-indigo-800">feedbacks da equipe</div></div></div>}</section>;
}

export function UsersPanel(){
 const [users,setUsers]=useState<AdminUser[]>([]);const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [role,setRole]=useState<Role>('MECHANIC');const [error,setError]=useState('');
 const load=async()=>setUsers((await json<{users:AdminUser[]}>(await api('/api/admin/users'))).users);useEffect(()=>{void load()},[]);
 const create=async(e:FormEvent)=>{e.preventDefault();setError('');try{await json(await api('/api/admin/users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password,role})}));setEmail('');setPassword('');await load()}catch(e){setError(e instanceof Error?e.message:'Erro ao criar usuário')}};
 const update=async(id:string,patch:object)=>{try{await json(await api(`/api/admin/users/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(patch)}));await load()}catch(e){setError(e instanceof Error?e.message:'Erro ao alterar usuário')}};
 return <section><p className="text-xs font-bold uppercase tracking-[.15em] text-indigo-600">Controle de acesso</p><h1 className="text-2xl font-bold mt-1">Usuários</h1><form onSubmit={create} className="bg-white border rounded-2xl p-5 mt-6"><div className="font-semibold mb-3">Novo acesso</div>{error&&<div className="text-sm text-rose-600 mb-3">{error}</div>}<div className="grid md:grid-cols-[1fr_1fr_180px_auto] gap-3"><input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="email@empresa.com" className="border rounded-xl px-3 py-2"/><input required minLength={6} type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Senha inicial" className="border rounded-xl px-3 py-2"/><select value={role} onChange={e=>setRole(e.target.value as Role)} className="border rounded-xl px-3 py-2"><option value="MECHANIC">Usuário da loja</option><option value="ADMIN">Administrador</option></select><button className="bg-indigo-600 text-white rounded-xl px-4 font-semibold">Criar</button></div></form><div className="bg-white border rounded-2xl overflow-x-auto mt-5"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-slate-500"><tr><th className="p-4">Usuário</th><th>Perfil</th><th>Status</th><th>Feedback</th><th className="p-4">Ações</th></tr></thead><tbody>{users.map(u=><tr key={u.id} className="border-t"><td className="p-4"><b>{u.email}</b><div className="text-xs text-slate-400">desde {fmtDate(u.createdAt)}</div></td><td>{u.role==='ADMIN'?'Administrador':'Usuário'}</td><td>{u.status}</td><td>{u.feedbackCount}</td><td className="p-4 flex gap-2"><button onClick={()=>update(u.id,{role:u.role==='ADMIN'?'MECHANIC':'ADMIN'})} className="border rounded-lg px-2 py-1">Trocar perfil</button><button onClick={()=>update(u.id,{status:u.status==='APPROVED'?'REJECTED':'APPROVED'})} className="border rounded-lg px-2 py-1">{u.status==='APPROVED'?'Bloquear':'Ativar'}</button></td></tr>)}</tbody></table></div></section>;
}

export function AuditPanel(){
 const [logs,setLogs]=useState<AuditLog[]>([]);useEffect(()=>{void (async()=>setLogs((await json<{logs:AuditLog[]}>(await api('/api/admin/audit'))).logs))()},[]);
 const label=(a:string)=>({DOCUMENT_UPLOADED:'Catálogo enviado',DOCUMENT_ARCHIVED:'Catálogo arquivado',DOCUMENT_RESTORED:'Catálogo restaurado',DOCUMENT_REPROCESSED:'Catálogo reprocessado',USER_CREATED:'Usuário criado',USER_UPDATED:'Usuário alterado'}[a]||a);
 return <section><p className="text-xs font-bold uppercase tracking-[.15em] text-indigo-600">Rastreabilidade</p><h1 className="text-2xl font-bold mt-1">Auditoria</h1><div className="bg-white border rounded-2xl mt-6 divide-y">{logs.map(l=><div key={l.id} className="p-4 flex flex-wrap justify-between gap-3"><div><b className="text-sm">{label(l.action)}</b><div className="text-xs text-slate-400 mt-1">{l.user?.email||'Sistema'} · {l.targetType}</div></div><div className="text-xs text-slate-500">{fmtDate(l.createdAt)}</div></div>)}{!logs.length&&<div className="p-8 text-sm text-slate-400 text-center">Nenhuma ação registrada.</div>}</div></section>;
}
