import { useEffect, useMemo, useState } from 'react';
import type { FormEvent } from 'react';
import { api, fmtDate, json } from '../lib';
import type { DocumentItem, FavoriteItem } from '../types';

export default function CatalogsPanel({admin}:{admin:boolean}){
 const [docs,setDocs]=useState<DocumentItem[]>([]); const [favorites,setFavorites]=useState<FavoriteItem[]>([]); const [search,setSearch]=useState(''); const [archived,setArchived]=useState(false); const [file,setFile]=useState<File|null>(null); const [manufacturer,setManufacturer]=useState(''); const [model,setModel]=useState(''); const [pnc,setPnc]=useState(''); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [notice,setNotice]=useState(''); const [pdf,setPdf]=useState<{url:string;title:string}|null>(null);
 const load=async()=>{try{const [r,f]=await Promise.all([api(`/api/documents${admin&&archived?'?includeArchived=true':''}`),api('/api/favorites')]);const d=await json<{documents:DocumentItem[]}>(r);const fav=await json<{favorites:FavoriteItem[]}>(f);setDocs(d.documents);setFavorites(fav.favorites);}catch(e){setError(e instanceof Error?e.message:'Erro ao carregar.')}};
 useEffect(()=>{void load();},[archived]);
 useEffect(()=>{if(!docs.some(d=>['PENDING','PROCESSING'].includes(d.status)))return;const t=setInterval(()=>void load(),5000);return()=>clearInterval(t);},[docs]);
 const filtered=useMemo(()=>docs.filter(d=>(archived||!d.archivedAt)&&[d.filename,d.manufacturer,d.model,d.pnc].some(v=>v?.toLowerCase().includes(search.toLowerCase()))),[docs,search,archived]);
 const favoriteFor=(documentId:string)=>favorites.find(f=>f.documentId===documentId);
 const flash=(text:string)=>{setNotice(text);window.setTimeout(()=>setNotice(''),1800)};
 const access=async(id:string,mode:'view'|'download',title='Catálogo')=>{try{const d=await json<{url:string}>(await api(`/api/documents/${id}/access?mode=${mode}`));if(mode==='view')setPdf({url:d.url,title});else window.open(d.url,'_blank','noopener,noreferrer')}catch(e){setError(e instanceof Error?e.message:'Não foi possível abrir o catálogo.')}};
 const toggleFavorite=async(doc:DocumentItem)=>{const current=favoriteFor(doc.id);if(current){await json(await api(`/api/favorites/${current.id}`,{method:'DELETE'}));flash('Catálogo removido dos favoritos.')}else{await json(await api('/api/favorites',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({documentId:doc.id})}));flash('Catálogo adicionado aos favoritos.')}await load()};
 const action=async(id:string,a:'archive'|'restore'|'reprocess')=>{setBusy(true);setError('');try{await json(await api(`/api/documents/${id}/${a}`,{method:'POST'}));await load();flash(a==='reprocess'?'Reprocessamento iniciado.':a==='archive'?'Catálogo arquivado.':'Catálogo restaurado.')}catch(e){setError(e instanceof Error?e.message:'Não foi possível concluir a ação.')}finally{setBusy(false)}};
 const upload=async(e:FormEvent)=>{e.preventDefault();if(!file)return;setBusy(true);setError('');const form=new FormData();form.append('file',file);if(manufacturer)form.append('manufacturer',manufacturer);if(model)form.append('model',model);if(pnc)form.append('pnc',pnc);try{await json(await api('/api/upload',{method:'POST',body:form}));setFile(null);setManufacturer('');setModel('');setPnc('');await load();flash('Catálogo enviado para processamento.')}catch(e){setError(e instanceof Error?e.message:'Erro no upload.')}finally{setBusy(false)}};
 const badge=(s:string)=>s==='COMPLETED'?'bg-emerald-50 text-emerald-700':s==='FAILED'?'bg-rose-50 text-rose-700':'bg-amber-50 text-amber-700';
 return <section>
 {notice&&<div className="fixed right-5 top-20 z-50 rounded-xl bg-slate-950 px-4 py-2.5 text-sm text-white shadow-xl">{notice}</div>}
 <div className="mb-6 flex flex-wrap justify-between gap-4"><div><p className="cv-kicker">Biblioteca técnica</p><h1 className="cv-page-title">Catálogos</h1><p className="mt-2 max-w-2xl text-sm text-slate-500">Consulte os manuais dentro do CogniVault, favorite os mais usados e acompanhe o processamento dos PDFs.</p></div>{admin&&<label className="flex items-center gap-2 text-sm text-slate-600"><input type="checkbox" checked={archived} onChange={e=>setArchived(e.target.checked)}/> Mostrar arquivados</label>}</div>
 {error&&<div className="mb-4 rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{error}</div>}
 {admin&&<form onSubmit={upload} className="cv-surface mb-6 rounded-[22px] p-5"><div className="mb-1 font-semibold">Adicionar catálogo</div><p className="mb-4 text-xs text-slate-400">Após o envio, a fila extrai e indexa as peças automaticamente.</p><div className="grid gap-3 md:grid-cols-4"><input type="file" accept="application/pdf" onChange={e=>setFile(e.target.files?.[0]||null)} required className="cv-field text-sm"/><input value={manufacturer} onChange={e=>setManufacturer(e.target.value)} placeholder="Fabricante" className="cv-field text-sm"/><input value={model} onChange={e=>setModel(e.target.value)} placeholder="Modelo" className="cv-field text-sm"/><input value={pnc} onChange={e=>setPnc(e.target.value)} placeholder="PNC (se souber)" className="cv-field text-sm"/></div><button disabled={busy} className="cv-primary mt-4 px-4 py-2.5 text-sm font-semibold">Enviar PDF</button></form>}
 <div className="cv-surface overflow-hidden rounded-[22px]"><div className="border-b border-slate-200 p-4"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar por arquivo, fabricante, modelo ou PNC" className="cv-field max-w-xl text-sm"/></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50/80 text-left text-[11px] uppercase tracking-[.08em] text-slate-400"><tr><th className="p-4">Catálogo</th><th>Modelo / PNC</th><th>Status</th><th>Peças</th><th className="p-4">Ações</th></tr></thead><tbody>{filtered.map(d=><tr key={d.id} className="border-t border-slate-100 transition hover:bg-slate-50/60"><td className="p-4"><div className="flex items-start gap-2"><button title="Favoritar" disabled={Boolean(d.archivedAt)} onClick={()=>void toggleFavorite(d)} className="text-lg leading-5 text-amber-500 disabled:opacity-30">{favoriteFor(d.id)?'★':'☆'}</button><div><b className="font-semibold text-slate-800">{d.filename}</b><div className="mt-1 text-xs text-slate-400">{d.manufacturer||'Fabricante não informado'} · {fmtDate(d.createdAt)}</div>{d.archivedAt&&<span className="text-xs text-rose-600">Arquivado</span>}</div></div></td><td className="text-slate-600">{d.model||'—'}<div className="text-xs text-slate-400">PNC {d.pnc||'—'}</div></td><td><span className={`rounded-full px-2 py-1 text-xs font-semibold ${badge(d.status)}`}>{d.status==='COMPLETED'?'Pronto':d.status==='PROCESSING'?'Processando':d.status==='PENDING'?'Na fila':'Falhou'}</span></td><td className="text-slate-600">{d.partCount}</td><td className="p-4"><div className="flex flex-wrap gap-2">{d.status==='COMPLETED'&&!d.archivedAt&&<><button onClick={()=>void access(d.id,'view',d.filename)} className="rounded-lg border border-slate-200 px-2.5 py-1.5 text-xs font-medium">Visualizar</button><button onClick={()=>void access(d.id,'download',d.filename)} className="rounded-lg border border-slate-200 px-2.5 py-1.5 text-xs font-medium">Baixar</button></>}{admin&&!d.archivedAt&&<><button disabled={busy} onClick={()=>void action(d.id,'reprocess')} className="rounded-lg border border-slate-200 px-2.5 py-1.5 text-xs font-medium">Reprocessar</button><button disabled={busy} onClick={()=>void action(d.id,'archive')} className="rounded-lg border border-rose-200 px-2.5 py-1.5 text-xs font-medium text-rose-600">Arquivar</button></>}{admin&&d.archivedAt&&<button disabled={busy} onClick={()=>void action(d.id,'restore')} className="rounded-lg border border-emerald-200 px-2.5 py-1.5 text-xs font-medium text-emerald-700">Restaurar</button>}</div></td></tr>)}</tbody></table>{!filtered.length&&<div className="p-10 text-center text-sm text-slate-400">Nenhum catálogo encontrado.</div>}</div></div>
 {pdf&&<div className="fixed inset-0 z-[90] bg-slate-950/90 p-3 md:p-6"><div className="mx-auto flex h-full max-w-[1500px] flex-col overflow-hidden rounded-[22px] bg-white"><div className="flex items-center justify-between border-b border-slate-200 px-4 py-3"><div><div className="text-sm font-semibold">{pdf.title}</div><div className="text-xs text-slate-400">Visualizador técnico</div></div><button onClick={()=>setPdf(null)} className="rounded-xl border border-slate-200 px-3 py-2 text-sm">Fechar</button></div><iframe title={pdf.title} src={pdf.url} className="h-full w-full border-0"/></div></div>}
 </section>;
}
