import { useEffect, useMemo, useState } from 'react';
import type { FormEvent } from 'react';
import { api, fmtDate, json } from '../lib';
import type { DocumentItem } from '../types';

export default function CatalogsPanel({admin}:{admin:boolean}){
 const [docs,setDocs]=useState<DocumentItem[]>([]); const [search,setSearch]=useState(''); const [archived,setArchived]=useState(false); const [file,setFile]=useState<File|null>(null); const [manufacturer,setManufacturer]=useState(''); const [model,setModel]=useState(''); const [pnc,setPnc]=useState(''); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
 const load=async()=>{try{const r=await api(`/api/documents${admin&&archived?'?includeArchived=true':''}`);const d=await json<{documents:DocumentItem[]}>(r);setDocs(d.documents);}catch(e){setError(e instanceof Error?e.message:'Erro ao carregar.')}};
 useEffect(()=>{void load();},[archived]);
 useEffect(()=>{if(!docs.some(d=>['PENDING','PROCESSING'].includes(d.status)))return;const t=setInterval(()=>void load(),5000);return()=>clearInterval(t);},[docs]);
 const filtered=useMemo(()=>docs.filter(d=>(archived||!d.archivedAt)&&[d.filename,d.manufacturer,d.model,d.pnc].some(v=>v?.toLowerCase().includes(search.toLowerCase()))),[docs,search,archived]);
 const access=async(id:string,mode:'view'|'download')=>{const d=await json<{url:string}>(await api(`/api/documents/${id}/access?mode=${mode}`));window.open(d.url,'_blank','noopener,noreferrer');};
 const action=async(id:string,a:'archive'|'restore'|'reprocess')=>{setBusy(true);try{await json(await api(`/api/documents/${id}/${a}`,{method:'POST'}));await load();}finally{setBusy(false)}};
 const upload=async(e:FormEvent)=>{e.preventDefault();if(!file)return;setBusy(true);setError('');const form=new FormData();form.append('file',file);if(manufacturer)form.append('manufacturer',manufacturer);if(model)form.append('model',model);if(pnc)form.append('pnc',pnc);try{await json(await api('/api/upload',{method:'POST',body:form}));setFile(null);setManufacturer('');setModel('');setPnc('');await load();}catch(e){setError(e instanceof Error?e.message:'Erro no upload.')}finally{setBusy(false)}};
 const badge=(s:string)=>s==='COMPLETED'?'bg-emerald-50 text-emerald-700':s==='FAILED'?'bg-rose-50 text-rose-700':'bg-amber-50 text-amber-700';
 return <section><div className="flex flex-wrap justify-between gap-4 mb-6"><div><p className="text-xs font-bold uppercase tracking-[.15em] text-indigo-600">Biblioteca técnica</p><h1 className="text-2xl font-bold mt-1">Catálogos PDF</h1><p className="text-sm text-slate-500 mt-2">Visualize e baixe as vistas explodidas disponíveis para sua equipe.</p></div>{admin&&<label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={archived} onChange={e=>setArchived(e.target.checked)}/> Mostrar arquivados</label>}</div>
 {error&&<div className="mb-4 bg-rose-50 text-rose-700 rounded-xl p-3 text-sm">{error}</div>}
 {admin&&<form onSubmit={upload} className="bg-white border border-slate-200 rounded-2xl p-5 mb-6"><div className="font-semibold mb-4">Adicionar catálogo</div><div className="grid md:grid-cols-4 gap-3"><input type="file" accept="application/pdf" onChange={e=>setFile(e.target.files?.[0]||null)} required className="text-sm border rounded-xl p-2"/><input value={manufacturer} onChange={e=>setManufacturer(e.target.value)} placeholder="Fabricante" className="border rounded-xl px-3 py-2 text-sm"/><input value={model} onChange={e=>setModel(e.target.value)} placeholder="Modelo" className="border rounded-xl px-3 py-2 text-sm"/><input value={pnc} onChange={e=>setPnc(e.target.value)} placeholder="PNC (se souber)" className="border rounded-xl px-3 py-2 text-sm"/></div><button disabled={busy} className="mt-4 bg-indigo-600 text-white rounded-xl px-4 py-2.5 text-sm font-semibold">Enviar PDF</button></form>}
 <div className="bg-white border border-slate-200 rounded-2xl overflow-hidden"><div className="p-4 border-b"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar por arquivo, fabricante, modelo ou PNC" className="w-full max-w-lg rounded-xl border border-slate-300 px-4 py-2.5 text-sm"/></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-slate-500 text-left"><tr><th className="p-4">Catálogo</th><th>Modelo / PNC</th><th>Status</th><th>Peças</th><th className="p-4">Ações</th></tr></thead><tbody>{filtered.map(d=><tr key={d.id} className="border-t border-slate-100"><td className="p-4"><b>{d.filename}</b><div className="text-xs text-slate-400 mt-1">{d.manufacturer||'Fabricante não informado'} · {fmtDate(d.createdAt)}</div>{d.archivedAt&&<span className="text-xs text-rose-600">Arquivado</span>}</td><td>{d.model||'—'}<div className="text-xs text-slate-400">PNC {d.pnc||'—'}</div></td><td><span className={`rounded-full px-2 py-1 text-xs font-semibold ${badge(d.status)}`}>{d.status==='COMPLETED'?'Pronto':d.status==='PROCESSING'?'Processando':d.status==='PENDING'?'Na fila':'Falhou'}</span></td><td>{d.partCount}</td><td className="p-4"><div className="flex flex-wrap gap-2">{d.status==='COMPLETED'&&!d.archivedAt&&<><button onClick={()=>access(d.id,'view')} className="border rounded-lg px-2 py-1">Ver</button><button onClick={()=>access(d.id,'download')} className="border rounded-lg px-2 py-1">Baixar</button></>}{admin&&!d.archivedAt&&<><button disabled={busy} onClick={()=>action(d.id,'reprocess')} className="border rounded-lg px-2 py-1">Reprocessar</button><button disabled={busy} onClick={()=>action(d.id,'archive')} className="text-rose-600 border border-rose-200 rounded-lg px-2 py-1">Arquivar</button></>}{admin&&d.archivedAt&&<button disabled={busy} onClick={()=>action(d.id,'restore')} className="text-emerald-700 border border-emerald-200 rounded-lg px-2 py-1">Restaurar</button>}</div></td></tr>)}</tbody></table>{!filtered.length&&<div className="p-10 text-center text-sm text-slate-400">Nenhum catálogo encontrado.</div>}</div></div>
 </section>;
}
